### ISSUE TITLE
DSSP returns KeyError8 on protein 5fb8

### ISSUE THREAD

**Issue by neb9** [graik/biskit#15]
```
Traceback (most recent call last):
  File "1.py", line 11, in <module>
    m = m.compress(m.maskProtein())	
  File "/home/dbmiller/scires/biskit/Biskit/PDBModel.py", line 2309, in compress
    return self.take( N0.nonzero( mask ), *initArgs, **initKw )
  File "/home/dbmiller/scires/biskit/Biskit/PDBModel.py", line 2249, in take
    r.biounit = self.biounit.take(i)
  File "/home/dbmiller/scires/biskit/Biskit/BioUnit.py", line 107, in take
    r.biomol = dict([ (bm , self.biomol[bm]) for bm in remaining_biomols ])
KeyError: 8

```

**Comment by neb9** [comment]
this issue did not exist in previous versions

**Comment by neb9** [comment]
Disregard previous comment. Applies equally to July commit build. Returns same result on 2q7n

**Comment by graik** [comment]
Sorry, didn't have time to look back into this. This can be relatively easily fixed by completely disabling the copying / extraction of biomol records in PDBModel.take. (See my previous comment somewhere). I plan to factor out the biomol code into its own module which should then only be run once on original PDB files. Didn't get to yet though.

**Comment by neb9** [comment]
Yeah, iirc, this happens even when I _do_ disable it per your instructions. So I think it's a different bug.

**Comment by graik** [comment]
addressed by biomol.take "deactivation"
